services:
  postgres:
    image: postgres:15-alpine
    container_name: misc-postgres
    environment:
      POSTGRES_USER: misc
      POSTGRES_PASSWORD: misc_password
      POSTGRES_DB: misc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U misc"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
